using Test
using Polymers

include("../src/physics/single_chain/test.jl")
include("../src/physics/single_chain/ideal/test.jl")
include("../src/physics/single_chain/ideal/thermodynamics/test.jl")
include("../src/physics/single_chain/ideal/thermodynamics/isometric/test.jl")
include("../src/physics/single_chain/ideal/thermodynamics/isotensional/test.jl")
include("../src/physics/single_chain/fjc/test.jl")
include("../src/physics/single_chain/fjc/thermodynamics/test.jl")
include("../src/physics/single_chain/fjc/thermodynamics/isometric/test.jl")
include("../src/physics/single_chain/fjc/thermodynamics/isometric/legendre/test.jl")
include("../src/physics/single_chain/fjc/thermodynamics/isotensional/test.jl")
include("../src/physics/single_chain/fjc/thermodynamics/isotensional/legendre/test.jl")
include("../src/physics/single_chain/fjc/thermodynamics/modified_canonical/test.jl")
include(
    "../src/physics/single_chain/fjc/thermodynamics/modified_canonical/asymptotic/test.jl",
)
include(
    "../src/physics/single_chain/fjc/thermodynamics/modified_canonical/asymptotic/strong_potential/test.jl",
)
include(
    "../src/physics/single_chain/fjc/thermodynamics/modified_canonical/asymptotic/weak_potential/test.jl",
)
include("../src/physics/single_chain/efjc/test.jl")
include("../src/physics/single_chain/efjc/thermodynamics/test.jl")
include("../src/physics/single_chain/efjc/thermodynamics/isometric/test.jl")
include("../src/physics/single_chain/efjc/thermodynamics/isometric/asymptotic/test.jl")
include(
    "../src/physics/single_chain/efjc/thermodynamics/isometric/asymptotic/legendre/test.jl",
)
include(
    "../src/physics/single_chain/efjc/thermodynamics/isometric/asymptotic/alternative/test.jl",
)
include(
    "../src/physics/single_chain/efjc/thermodynamics/isometric/asymptotic/alternative/legendre/test.jl",
)
include(
    "../src/physics/single_chain/efjc/thermodynamics/isometric/asymptotic/reduced/test.jl",
)
include(
    "../src/physics/single_chain/efjc/thermodynamics/isometric/asymptotic/reduced/legendre/test.jl",
)
include("../src/physics/single_chain/efjc/thermodynamics/isotensional/test.jl")
include("../src/physics/single_chain/efjc/thermodynamics/isotensional/legendre/test.jl")
include("../src/physics/single_chain/efjc/thermodynamics/isotensional/asymptotic/test.jl")
include(
    "../src/physics/single_chain/efjc/thermodynamics/isotensional/asymptotic/legendre/test.jl",
)
include(
    "../src/physics/single_chain/efjc/thermodynamics/isotensional/asymptotic/alternative/test.jl",
)
include(
    "../src/physics/single_chain/efjc/thermodynamics/isotensional/asymptotic/alternative/legendre/test.jl",
)
include(
    "../src/physics/single_chain/efjc/thermodynamics/isotensional/asymptotic/reduced/test.jl",
)
include(
    "../src/physics/single_chain/efjc/thermodynamics/isotensional/asymptotic/reduced/legendre/test.jl",
)
include("../src/physics/single_chain/swfjc/test.jl")
include("../src/physics/single_chain/swfjc/thermodynamics/test.jl")
include("../src/physics/single_chain/swfjc/thermodynamics/isometric/test.jl")
include("../src/physics/single_chain/swfjc/thermodynamics/isometric/legendre/test.jl")
include("../src/physics/single_chain/swfjc/thermodynamics/isotensional/test.jl")
include("../src/physics/single_chain/swfjc/thermodynamics/isotensional/legendre/test.jl")
include("../src/physics/single_chain/ufjc/test.jl")
include("../src/physics/single_chain/ufjc/lennard_jones/test.jl")
include("../src/physics/single_chain/ufjc/lennard_jones/thermodynamics/test.jl")
include("../src/physics/single_chain/ufjc/lennard_jones/thermodynamics/isometric/test.jl")
include(
    "../src/physics/single_chain/ufjc/lennard_jones/thermodynamics/isometric/asymptotic/test.jl",
)
include(
    "../src/physics/single_chain/ufjc/lennard_jones/thermodynamics/isometric/asymptotic/legendre/test.jl",
)
include(
    "../src/physics/single_chain/ufjc/lennard_jones/thermodynamics/isometric/asymptotic/reduced/test.jl",
)
include(
    "../src/physics/single_chain/ufjc/lennard_jones/thermodynamics/isometric/asymptotic/reduced/legendre/test.jl",
)
include(
    "../src/physics/single_chain/ufjc/lennard_jones/thermodynamics/isotensional/test.jl",
)
include(
    "../src/physics/single_chain/ufjc/lennard_jones/thermodynamics/isotensional/legendre/test.jl",
)
include(
    "../src/physics/single_chain/ufjc/lennard_jones/thermodynamics/isotensional/asymptotic/test.jl",
)
include(
    "../src/physics/single_chain/ufjc/lennard_jones/thermodynamics/isotensional/asymptotic/legendre/test.jl",
)
include(
    "../src/physics/single_chain/ufjc/lennard_jones/thermodynamics/isotensional/asymptotic/reduced/test.jl",
)
include(
    "../src/physics/single_chain/ufjc/lennard_jones/thermodynamics/isotensional/asymptotic/reduced/legendre/test.jl",
)
include("../src/physics/single_chain/ufjc/log_squared/test.jl")
include("../src/physics/single_chain/ufjc/log_squared/thermodynamics/test.jl")
include("../src/physics/single_chain/ufjc/log_squared/thermodynamics/isometric/test.jl")
include(
    "../src/physics/single_chain/ufjc/log_squared/thermodynamics/isometric/asymptotic/test.jl",
)
include(
    "../src/physics/single_chain/ufjc/log_squared/thermodynamics/isometric/asymptotic/legendre/test.jl",
)
include(
    "../src/physics/single_chain/ufjc/log_squared/thermodynamics/isometric/asymptotic/reduced/test.jl",
)
include(
    "../src/physics/single_chain/ufjc/log_squared/thermodynamics/isometric/asymptotic/reduced/legendre/test.jl",
)
include("../src/physics/single_chain/ufjc/log_squared/thermodynamics/isotensional/test.jl")
include(
    "../src/physics/single_chain/ufjc/log_squared/thermodynamics/isotensional/legendre/test.jl",
)
include(
    "../src/physics/single_chain/ufjc/log_squared/thermodynamics/isotensional/asymptotic/test.jl",
)
include(
    "../src/physics/single_chain/ufjc/log_squared/thermodynamics/isotensional/asymptotic/legendre/test.jl",
)
include(
    "../src/physics/single_chain/ufjc/log_squared/thermodynamics/isotensional/asymptotic/reduced/test.jl",
)
include(
    "../src/physics/single_chain/ufjc/log_squared/thermodynamics/isotensional/asymptotic/reduced/legendre/test.jl",
)
include("../src/physics/single_chain/ufjc/morse/test.jl")
include("../src/physics/single_chain/ufjc/morse/thermodynamics/test.jl")
include("../src/physics/single_chain/ufjc/morse/thermodynamics/isometric/test.jl")
include(
    "../src/physics/single_chain/ufjc/morse/thermodynamics/isometric/asymptotic/test.jl",
)
include(
    "../src/physics/single_chain/ufjc/morse/thermodynamics/isometric/asymptotic/legendre/test.jl",
)
include(
    "../src/physics/single_chain/ufjc/morse/thermodynamics/isometric/asymptotic/reduced/test.jl",
)
include(
    "../src/physics/single_chain/ufjc/morse/thermodynamics/isometric/asymptotic/reduced/legendre/test.jl",
)
include("../src/physics/single_chain/ufjc/morse/thermodynamics/isotensional/test.jl")
include(
    "../src/physics/single_chain/ufjc/morse/thermodynamics/isotensional/legendre/test.jl",
)
include(
    "../src/physics/single_chain/ufjc/morse/thermodynamics/isotensional/asymptotic/test.jl",
)
include(
    "../src/physics/single_chain/ufjc/morse/thermodynamics/isotensional/asymptotic/legendre/test.jl",
)
include(
    "../src/physics/single_chain/ufjc/morse/thermodynamics/isotensional/asymptotic/reduced/test.jl",
)
include(
    "../src/physics/single_chain/ufjc/morse/thermodynamics/isotensional/asymptotic/reduced/legendre/test.jl",
)
include("../src/physics/single_chain/ufjc/composite/test.jl")
include("../src/physics/single_chain/ufjc/composite/thermodynamics/test.jl")
include("../src/physics/single_chain/ufjc/composite/thermodynamics/isometric/test.jl")
include("../src/physics/single_chain/ufjc/composite/thermodynamics/isometric/legendre/test.jl")
include("../src/physics/single_chain/ufjc/composite/thermodynamics/isotensional/test.jl")
include("../src/physics/single_chain/ufjc/composite/thermodynamics/isotensional/legendre/test.jl")
include("../src/physics/single_chain/wlc/test.jl")
include("../src/physics/single_chain/wlc/thermodynamics/test.jl")
include("../src/physics/single_chain/wlc/thermodynamics/isometric/test.jl")
include("../src/physics/single_chain/wlc/thermodynamics/isometric/legendre/test.jl")
include("../src/physics/single_chain/wlc/thermodynamics/isotensional/test.jl")
include("../src/physics/single_chain/wlc/thermodynamics/isotensional/legendre/test.jl")