using Test
using Polymers

include("../src/physics/single_chain/ideal/test.jl")
include("../src/physics/single_chain/ideal/thermodynamics/test.jl")
include("../src/physics/single_chain/ideal/thermodynamics/isometric/test.jl")
include("../src/physics/single_chain/fjc/test.jl")
include("../src/physics/single_chain/fjc/thermodynamics/test.jl")
include("../src/physics/single_chain/fjc/thermodynamics/isometric/test.jl")
include("../src/physics/single_chain/fjc/thermodynamics/isometric/legendre/test.jl")
include("../src/physics/single_chain/fjc/thermodynamics/isotensional/test.jl")
include("../src/physics/single_chain/fjc/thermodynamics/isotensional/legendre/test.jl")
include("../src/physics/single_chain/fjc/thermodynamics/modified_canonical/test.jl")
include("../src/physics/single_chain/fjc/thermodynamics/modified_canonical/asymptotic/test.jl")
include("../src/physics/single_chain/fjc/thermodynamics/modified_canonical/asymptotic/strong_potential/test.jl")
include("../src/physics/single_chain/fjc/thermodynamics/modified_canonical/asymptotic/weak_potential/test.jl")
#include("../src/physics/single_chain/efjc/test.jl")
#include("../src/physics/single_chain/efjc/thermodynamics/test.jl")
#include("../src/physics/single_chain/efjc/thermodynamics/isotensional/test.jl")
#include("../src/physics/single_chain/efjc/thermodynamics/isotensional/legendre/test.jl")
#include("../src/physics/single_chain/efjc/thermodynamics/isotensional/asymptotic/test.jl")
#include("../src/physics/single_chain/efjc/thermodynamics/isotensional/asymptotic/legendre/test.jl")
#include("../src/physics/single_chain/efjc/thermodynamics/isotensional/asymptotic/alternative/test.jl")
#include("../src/physics/single_chain/efjc/thermodynamics/isotensional/asymptotic/alternative/legendre/test.jl")
#include("../src/physics/single_chain/efjc/thermodynamics/isotensional/asymptotic/reduced/test.jl")
#include("../src/physics/single_chain/efjc/thermodynamics/isotensional/asymptotic/reduced/legendre/test.jl")
include("../src/physics/single_chain/swfjc/test.jl")
include("../src/physics/single_chain/swfjc/thermodynamics/test.jl")
include("../src/physics/single_chain/swfjc/thermodynamics/isotensional/test.jl")
include("../src/physics/single_chain/swfjc/thermodynamics/isotensional/legendre/test.jl")
