version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    rust: "1.64"
  jobs:
    pre_install:
      - pip install cffi maturin
sphinx:
  configuration: docs/source/conf.py
python:
  install:
  - method: pip
    path: .