version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    rust: "1.64"
  commands:
    - pip install maturin
    - maturin build --features python
    - pip install target/wheels/*.whl
    - pip install -r docs/requirements.txt
    - cd docs/ && make html
    - mkdir _readthedocs/
    - mv docs/build/html/ _readthedocs/
