version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    rust: "1.64"
  commands:
    - pip install cffi maturin
    - cargo build --features python
    - maturin build --features python
sphinx:
  configuration: docs/source/conf.py
python:
  install:
  - method: pip
    path: .