version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    rust: "1.64"
  commands:
    - pip install -r docs/requirements.txt
    - maturin build --features python
    - pip install target/wheels/*.whl
    - cd docs/ && make html
    - ls -ltrah docs/
sphinx:
  configuration: docs/source/conf.py
python:
  install:
  - requirements: docs/requirements.txt
  - method: pip
    path: .
