version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    rust: "1.64"
  # commands:
  #   - pip install cffi maturin
  #   - cargo build --features python
  #   - maturin build --features python
  #   - pip install polymers
sphinx:
  configuration: docs/source/conf.py
python:
  install:
  - requirements: docs/requirements.txt
  - method: pip
    path: .