package:
  name: "polymers"
  version: "VERSION_PLACEHOLDER"
source:
  git_depth: 1
  git_url: https://github.com/sandialabs/Polymers
build:
#   noarch: python
  number: 1
  script: |
    maturin build --features python
    pip install --no-deps target/wheels/*.whl
#     julia -e 'using Pkg; Pkg.develop(path="."); Pkg.build("Polymers")'
requirements:
  build:
#     - julia
    - maturin
    - pip
    - python
    - rust
  run:
#     - julia
    - python
# test:
#   imports:
#     - polymers
about:
  dev_url: https://github.com/sandialabs/Polymers
  home: https://sandialabs.github.io/Polymers
  license: BSD-3-Clause
  license_file: LICENSE
  license_url: https://github.com/sandialabs/polymers/blob/main/LICENSE
  summary: Polymers Modeling Library