[package]
name = "polymers"
version = "0.0.5"
edition = "2021"
description = "Polymers Modeling Library"
license = "BSD-3-Clause"
keywords = ["python", "rust", "polymers"]

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]

[features]
python = ["dep:pyo3"]

[dependencies]
pyo3 = {version = "0.17.3", features = ["extension-module"], optional = true}

[dev-dependencies]
rand = "0.8.5"
