name: polymers
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - python
  - rust=1.65.0
  - pip:
    - cffi==1.15.1
    - matplotlib
    - maturin==0.14.9
    - numpy
    - polymers
    - scipy