name: polymers
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - julia
  - pip
  - python
  - rust=1.65.0
  - pip:
    - cffi
    - matplotlib
    - maturin
    - numpy
    - polymers
    - scipy
