name: polymers
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pip=22.1.2
  - python=3.10.4
  - rust=1.65.0
  - pip:
    - cffi==1.15.1
    - maturin==0.14.8
    - polymers==0.0.5