name: Julia
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ published ]
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.8
      - name: add
        run: julia -e 'using Pkg; Pkg.add(path=".")'
      - name: build
        run: julia -e 'using Pkg; Pkg.build("Polymers")'
      - name: test
        run: julia -e 'using Pkg; Pkg.test("Polymers")'
      - name: format
        run: julia -e 'using Pkg; Pkg.add("JuliaFormatter"); using JuliaFormatter; if format("./") == true; exit(0); else exit(1); end'
