name: Julia
on:
  push:
    branches: [ "workflow-repairs" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ published ]
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    if: github.event_name != 'release'
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.8
      - name: test
        if: runner.os == 'Windows'
        run: julia -e 'using Pkg; Pkg.add(path=\".\"); Pkg.test(\"Polymers\")'
      - name: test
        if: runner.os != 'Windows'
        run: julia -e 'using Pkg; Pkg.add(path="."); Pkg.test("Polymers")'
      - name: aqua
        if: runner.os == 'Linux'
        run: |
          julia -e 'using Pkg; Pkg.add("Aqua")'
          julia -e 'using Polymers; using Aqua; Aqua.test_all(Polymers)'
      - name: format
        if: runner.os == 'Linux'
        run: |
          julia -e 'using Pkg; Pkg.add("JuliaFormatter")'
          julia -e 'using JuliaFormatter; if format(".", overwrite=false, verbose=true) == true; exit(0); else exit(1); end'
  register:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: '@JuliaRegistrator register'
            })
