name: Version
on:
  push:
   branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: get
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
          view_top: 1
      - name: check
        run: |
          export LATEST_VERSION=$(echo ${{ steps.last_release.outputs.tag_name }} | cut -d v -f 2)
          echo "latest tag is ${LATEST_VERSION}"
          export CURRENT_VERSION=$(grep -m 1 version Cargo.toml | cut -d '"' -f 2)
          echo "version in PR is ${CURRENT_VERSION}"
          pip install packaging
          export CHECK=$(python -c 'from packaging.version import parse; print(parse("'${CURRENT_VERSION}'") > parse("'${LATEST_VERSION}'"))' | tr '[:upper:]' '[:lower:]')
          $CHECK